[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "cerulean"
ADMIN_NAME = "Econovolt [Projeto Integrador - Grupo 63]"
ADMIN_TEMPLATE_MODE = "bootstrap2"
EXTENSIONS = [
    "app.ext.db:init_app",
    "app.ext.main:init_app",
    "app.ext.auth:init_app", 
    "app.ext.admin:init_app", 
    "app.ext.migrate:init_app", 
    "app.ext.cli:init_app", 
    "app.ext.site:init_app",
    "app.ext.mail:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///econovolt.db" 
SQLALCHEMY_TRACK_MODIFICATIONS = false 
ADMIN_NAME = "Econovolt (dev mode)"
EXTENSIONS = [
    "app.ext.db:init_app",
    "app.ext.main:init_app",
    "app.ext.auth:init_app", 
    "app.ext.admin:init_app", 
    "app.ext.migrate:init_app", 
    "app.ext.cli:init_app",
    "app.ext.toolbar:init_app", 
    "app.ext.site:init_app",  
    "app.ext.mail:init_app",  
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "sqlite:///econovolt.db" 
