"""add on_menu to Simulation

Revision ID: bf7626cacaea
Revises: 
Create Date: 2022-05-16 14:05:29.879891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7626cacaea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Simulation', sa.Column('on_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Simulation', 'on_menu')
    # ### end Alembic commands ###
