"""empty message

Revision ID: c1c9bf6ed930
Revises: a1759e0046a4
Create Date: 2022-05-27 14:30:04.857171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c9bf6ed930'
down_revision = 'a1759e0046a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
